language: cpp
system: linux

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib  
  - sudo apt-get install -y build-essential  
  - sudo apt-get install -y fpc  
  - sudo apt-get install -y qemu  
  - sudo apt-get install -y unzip 

script:  
  - cd ..
  - wget ftp://ftp.gnu.org/gnu/binutils/binutils-2.29.1.tar.bz2  
  - tar xvjf binutils-2.29.1.tar.bz2  
  - cd binutils-2.29.1  
  - ./configure --target=m68k-elf --prefix=$(pwd)/../binutils  
  - make  
  - make install
  - cd ..
  - wget https://github.com/newpascal/freepascal/archive/freepascal.zip  
  - unzip freepascal.zip  
  - cd freepascal-freepascal  
  - make all  
  - make install INSTALL_PREFIX=$(pwd)/../fpc  
  - PATH=$(pwd)/../binutils/bin:$PATH make all CPU_TARGET=m68k OS_TARGET=linux CROSSOPT="-O- -Cpisac" BINUTILSPREFIX=m68k-elf-  
  - make crossinstall OS_TARGET=linux CPU_TARGET=m68k INSTALL_PREFIX=$(pwd)/../fpc  
  - $(pwd)/../fpc/bin/fpcmkcfg -d basepath=$(pwd)/../fpc/lib/fpc/3.1.1 -d sharepath=$(pwd)/../fpc/lib/fpc/3.1.1 -o $(pwd)/../fpc/lib/fpc/3.1.1/fpc.cfg 
  - cd $(pwd)/../fpc/lib/fpc/3.1.1  
  - echo "-Fu$(pwd)/units/m68k-linux" >> fpc.cfg 
  - echo "-Fu$(pwd)/units/m68k-linux/*" >> fpc.cfg 
  - echo "-Fu$(pwd)/units/m68k-linux/rtl" >> fpc.cfg 
  - cd ../../../..
  - echo 'timeout -k 2s 60s qemu-m68k -cpu cfv4e $@' >> run-qemu-m68k
  - chmod +x run-qemu-m68k
  - cd freepascal-freepascal/tests/
  - PATH=$(pwd)/../../binutils/bin:$PATH make clean full TEST_FPC=$(pwd)/../../fpc/lib/fpc/3.1.1/ppcross68k TEST_OPT="-O- -Cpisac -XPm68k-elf-" EMULATOR=$(pwd)/../../run-qemu-m68k CHUNKSIZE=50 -j 2  