language: cpp

os:
  - linux

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib  
  - sudo apt-get install -y build-essential  
  - sudo apt-get install -y fpc  
  - sudo apt-get install -y qemu  
  - sudo apt-get install -y unzip 

script:  
  - cd /usr/local
  - sudo wget ftp://ftp.gnu.org/gnu/binutils/binutils-2.29.1.tar.bz2  
  - sudo tar xvjf binutils-2.29.1.tar.bz2  
  - cd binutils-2.29.1  
  - sudo ./configure --target=m68k-elf --prefix=/usr/local/binutils  
  - sudo make  
  - sudo make install
  - cd ..
  - sudo wget https://github.com/newpascal/freepascal/archive/freepascal.zip  
  - sudo unzip freepascal.zip  
  - cd freepascal-freepascal  
  - sudo make all  
  - sudo make install INSTALL_PREFIX=/usr/local/fpc  
  - sudo PATH=/usr/local/binutils/bin:$PATH make all CPU_TARGET=m68k OS_TARGET=linux CROSSOPT="-O- -Cpisac" BINUTILSPREFIX=m68k-elf-  
  - sudo make crossinstall OS_TARGET=linux CPU_TARGET=m68k INSTALL_PREFIX=/usr/local/fpc  
  - cd /usr/local/fpc/lib/fpc/3.1.1  
  - sudo /usr/local/fpc/bin/fpcmkcfg -d basepath=/usr/local/fpc/lib/fpc/3.1.1 -d sharepath=/usr/local/fpc/lib/fpc/3.1.1 -o ./fpc.cfg 
  - sudo echo "-Fu$(pwd)/units/m68k-linux" >> fpc.cfg 
  - sudo echo "-Fu$(pwd)/units/m68k-linux/*" >> fpc.cfg 
  - sudo echo "-Fu$(pwd)/units/m68k-linux/rtl" >> fpc.cfg 
  - sudo echo 'timeout -k 2s 60s qemu-m68k -cpu cfv4e $@' >> /usr/local/run-qemu-m68k
  - sudo chmod +x /usr/local/run-qemu-m68k
  - cd /usr/local/freepascal-freepascal/tests/
  - sudo PATH=/usr/local/binutils/bin:$PATH make clean full TEST_FPC=/usr/local/fpc/lib/fpc/3.1.1/ppcross68k TEST_OPT="-O- -Cpisac -XPm68k-elf-" EMULATOR=/usr/local/run-qemu-m68k CHUNKSIZE=50 -j 1  