language: cpp
system: linux

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib  
  - sudo apt-get install -y build-essential  
  - sudo apt-get install -y qemu  
  - sudo apt-get install -y unzip 

script:
# initialization for basic variables
  - cd ..
  - main_dir=`pwd`
  - fpc_base_dir=$main_dir'/fpc/lib/fpc/3.1.1'
  - PATH=$main_dir/binutils/bin:$PATH
  - bootstrap=FPC=$main_dir/bootstrap/ppcx64-linux
  - installprefix=INSTALL_PREFIX=$main_dir/fpc
# download bootstrap compiler
  - mkdir bootstrap
  - cd bootstrap
  - wget https://github.com/maciej-izak/fpc-ci-tests/releases/download/bootstrap/ppcx64-linux
  - chmod +x ppcx64-linux
  - cd $main_dir  
# download and build binutils  
  - wget ftp://ftp.gnu.org/gnu/binutils/binutils-2.29.1.tar.bz2  
  - tar xvjf binutils-2.29.1.tar.bz2
  - cd binutils-2.29.1  
  - ./configure --target=m68k-elf --prefix=$main_dir/binutils  
  - make  
  - make install
  - cd $main_dir  
# download and build fpc
  - wget https://github.com/newpascal/freepascal/archive/freepascal.zip  
  - unzip freepascal.zip  
  - cd freepascal-freepascal  
  - make all install $bootstrap $installprefix 
  - make all crossinstall CPU_TARGET=m68k OS_TARGET=linux CROSSOPT="-O- -Cpisac" BINUTILSPREFIX=m68k-elf- $bootstrap $installprefix 
  - $main_dir/fpc/bin/fpcmkcfg -d basepath=$fpc_base_dir -d sharepath=$fpc_base_dir -o $fpc_base_dir/fpc.cfg 
  - cd $fpc_base_dir  
  - echo "-Fu$fpc_base_dir/units/m68k-linux" >> fpc.cfg 
  - echo "-Fu$fpc_base_dir/units/m68k-linux/*" >> fpc.cfg 
  - echo "-Fu$fpc_base_dir/units/m68k-linux/rtl" >> fpc.cfg
  - cd $main_dir  
# test for m68k 
  - echo 'timeout -k 2s 60s qemu-m68k -cpu cfv4e $@' >> run-qemu-m68k
  - chmod +x run-qemu-m68k
  - cd freepascal-freepascal/tests/
  - make full TEST_FPC=$fpc_base_dir/ppcross68k TEST_OPT="-O- -Cpisac -XPm68k-elf-" EMULATOR=$main_dir/run-qemu-m68k CHUNKSIZE=50 -j 2  