# This file is part of the Free Pascal CI system.
# Copyright (c) 2017 by Maciej Izak
# member of the Free Pascal development team

language: cpp
system: linux

env:
  global:
    # number of CPU cores
    - J=2

matrix:
  include:
    - env:
        - CPUTARGET=i386
        - TEST_MAIN_PARAMS="full"
    - env:
        - CPUTARGET=x86_64
        - TEST_MAIN_PARAMS="full"
    - env:
        - CPUTARGET=avr
        - TEST_MAIN_PARAMS="full"
    - env:
        - CPUTARGET=m68k
        - TEST_MAIN_PARAMS="full"
    - env:
        - CPUTARGET=i8086
        - TEST_MAIN_PARAMS="allexectbs SINGLEDOTESTRUNS=1"
    - env:
        - CPUTARGET=i8086
        - TEST_MAIN_PARAMS="allexectbf SINGLEDOTESTRUNS=1"
    - env:
        - CPUTARGET=i8086
        - TEST_MAIN_PARAMS="allexecwebtbs SINGLEDOTESTRUNS=1"
    - env:
        - CPUTARGET=i8086
        - TEST_MAIN_PARAMS="allexecwebtbf SINGLEDOTESTRUNS=1"
    - env:
        - CPUTARGET=i8086
        - TEST_MAIN_PARAMS="allexectest SINGLEDOTESTRUNS=1"

install:
  - if [ $CPUTARGET = i8086 ]; then sudo dpkg --add-architecture i386; fi
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y unzip
  - if [ $CPUTARGET = m68k ]; then sudo apt-get install -y qemu; fi
  - if [ $CPUTARGET = i8086 ]; then sudo apt-get install -y dosbox:i386; fi

script:
# initialization for basic variables
  - export TEST_MAIN_PARAMS=($TEST_MAIN_PARAMS)
  - export main_dir=`pwd`
  - export fpc_base_dir=$main_dir'/fpc/lib/fpc/3.1.1'
  - export PATH=$main_dir/binutils/bin:$main_dir/fpc/bin:$fpc_base_dir:$PATH
  - export bootstrap=FPC=$main_dir/bootstrap/ppcx64-linux
  - export installprefix=INSTALL_PREFIX=$main_dir/fpc
# download bootstrap compiler
  - mkdir bootstrap
  - cd bootstrap
  - wget https://github.com/maciej-izak/fpc-ci-tests/releases/download/bootstrap/ppcx64-linux
  - chmod ugo+x ppcx64-linux
  - cd $main_dir
# script with basic variables
  - chmod ugo+x fpcvariables.sh
# download and build binutils for some targets
  - chmod ugo+x binutils.sh
  - ./binutils.sh
# download and build fpc
  - chmod ugo+x buildfpctrunk.sh
  - ./buildfpctrunk.sh
# build selected ppcross
  - chmod ugo+x buildfpccrosstrunk.sh
  - ./buildfpccrosstrunk.sh
# tests
  - chmod ugo+x testfpc.sh
  - ./testfpc.sh
# possible results output/ 
# x86_64-linux : i386-linux : m68k-linux : msdos : avr-embedded
# normal test : faillist, log, longlog
# dos has result in 3 files (each matrix), for example for allexectbs
# faillist.tbslog
# log.tbslog
# longlog.tbslog
